Portfolio: setup and mobile version skeleton
jorgegoco/my-first-portfolio pull request #1
Opened 2022-04-21 17:29 UTC by jorgegoco

##Portfolio: setup and mobile version skeleton

In this first pull request:

 #Added the configuration files
 #Added the HTML and CSS files for this initial part of the project

2022-04-21 19:37 UTC, KayLemba requested changes
Hi @jorgegoco   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️
PR has a title and summary. ✔️
Required Changes ♻️
Check the comments under the review.

 - Please add a descriptive README file to your project, Feel free to use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-21 19:37 UTC, KayLemba commented on mobile.html
> +    <li class="icon"><img src="./images/medium.svg" alt=""></li>
Kindly add a background image please follow the guide lines on figma for the template you chose use exact font colors, font size, font weight etc. 
This is how your design looks:
![Screenshot from 2022-04-21 23-08-47](https://user-images.githubusercontent.com/79506105/164536262-1547a480-ecd9-422a-8c5c-98d2b969d51b.png)
 Your web page should look like this:
![Screenshot from 2022-04-21 23-11-21](https://user-images.githubusercontent.com/79506105/164536410-905ffeda-b938-4d8f-a22d-1ad320311952.png)
Kindly stick to the design on figma

2022-04-21 19:37 UTC, KayLemba commented on mobile.css
> +}
Kindly add a gap to space out your social media icons: please follow the design below
![Screenshot from 2022-04-21 23-11-21](https://user-images.githubusercontent.com/79506105/164536771-2f2ab48c-7e4c-4f5e-bf5a-6b96e83c23b7.png)
Please Inspect the template carefully.

2022-04-21 19:37 UTC, KayLemba commented on mobile.html
> +    <li class="icon"><img src="./images/medium.svg" alt=""></li>
I can see you are missing out something in you README file. Kindly add a description about the project , Please add how to access you project locally give instructions and add a screen shot of you webpage UI. This will make your README.file look professional.

2022-04-22 19:52 UTC, zieeco requested changes
Hi @jorgegoco 

 <img src="https://media3.giphy.com/media/YT95XJOLvY1t2SJgpR/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Nice design :heavy_check_mark: 
- No linter error :heavy_check_mark: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 19:52 UTC, zieeco commented on mobile.html
> +    <li class="icon"><img src="./images/medium.svg" alt=""></li>
- [ ] **[REQUIRED CHANGES]**

Hey, great job implementing the changes required by the previous reviewer, however, you're still missing the background image. Below is your design :point_down: 

![127 0 0 1_5500_mobile html](https://user-images.githubusercontent.com/59397159/164783117-5090c711-bdb3-446c-b973-a73595fcec4f.png)

- [ ] **Try adding the background image.** refer to your design from [FIGMA](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468)

- [ ] Also, as required by the previous reviewer, kindly add the missing headers in your readme and update them accordingly depending on what is relevant to your project. check the [microverse readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) for guidelines.

2022-04-26 13:17 UTC, MeqdamAlqudah approved these changes
Hi @jorgegoco , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/13zeE9qQNC5IKk/giphy.webp?cid=ecf05e4745cjfwa9748zlpca9zmxzxrvi7d3lhgdp9c6046k&rid=giphy.webp&ct=g)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 13:20 UTC, jorgegoco commented
Thank you!

2022-04-27 07:59 UTC, merged